FROM nginx:latest

MAINTAINER iscmyoo <sung32114@gmail.com>

#RUN rm /etc/nginx/conf.d/default.conf
#COPY /capstone_design/nginx/etc/project.conf /etc/nginx/conf.d/

RUN rm /etc/nginx/nginx.conf
COPY ./capstone_design/nginx/etc/project.conf /etc/nginx/nginx.conf