name: build docker image

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

#환경설정
env:
  DOCKER_FASTAPI_IMAGE: ghcr.io/kookmin-sw/capstone-2024-09/capstone_design-fastapi_develop
  DOCKER_REACT_IMAGE: ghcr.io/kookmin-sw/capstone-2024-09/capstone_design-react_develop
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.10"]
    steps:
      # github repository에서 checkout
      - name: checkout
        uses: actions/checkout@v4

      # docker를 사용하기 위한 기본 세팅
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_CI_CD_TOKEN }}
      # push and docker layer cache 저장하기

      # fastapi app image build and push
      - name: Build fastapi image and push
        id: docker_build_flask
        uses: docker/build-push-action@v5
        with:
          file: ./capstone_design/fastapi_app/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_FASTAPI_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # react app image build and push
      - name: Build react image and push
        id: docker_build_react
        uses: docker/build-push-action@v5
        with:
          file: ./capstone_design/react_app/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_REACT_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: build
    name: Deploy docker image
    runs-on: [self-hosted, label-test]
    steps:
      # github repository에서 checkout
      - name: checkout
        uses: actions/checkout@v4
      # docker-compose.yml 파일 옮기기
      - name: Deploy docker_compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: './docker-compose.yml'
          target: '/home/ubuntu'
      # ghcr 로그인
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_CI_CD_TOKEN }}
      # docker run
      - name: Docker run
        run: |
          docker rm -f $(docker ps -a -q)
          docker rmi -f $(docker images -q)
          docker pull ${{ env.DOCKER_FASTAPI_IMAGE }}:latest && docker pull ${{ env.DOCKER_REACT_IMAGE }}:latest && docker pull ${{ env.DOCKER_NGINX_IMAGE }}:latest
          cd /home/ubuntu
          docker-compose -f docker-compose.yml --env-file .env up --build -d
